<a href="https://colab.research.google.com/github/SauleRub/DI_Bootcamp/blob/main/Week10/Day5/Week10_Day5_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercise 1: Array Creation and Manipulation

In [1]:
import numpy as np

array1 = np.arange(10)

print(array1)

[0 1 2 3 4 5 6 7 8 9]


Exercise 2: Type Conversion and Array Operations

In [2]:
my_list = [3.14, 2.17, 0, 1, 2]

array2 = np.array(my_list).astype(int)

print(array2)

[3 2 0 1 2]


Exercise 3: Working with Multi-Dimensional Arrays

In [3]:
# 3x3 array with values from 1 to 9
array3 = np.arange(1, 10).reshape(3, 3)

print(array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Exercise 4: Creating Multi-Dimensional Array with Random Numbers

In [4]:
# 4x5 array with random numbers
random_array = np.random.rand(4, 5)

print(random_array)

[[0.22150664 0.89729887 0.72567193 0.45531699 0.06675033]
 [0.94857578 0.34569519 0.30420664 0.02284188 0.56900922]
 [0.02031348 0.78968549 0.34265819 0.01352318 0.14563484]
 [0.46749215 0.8144109  0.43902438 0.20166432 0.42028477]]


Exercise 5: Indexing Arrays

In [5]:
array = np.array([[21, 22, 23, 22, 22],
                  [20, 21, 22, 23, 24],
                  [21, 22, 23, 22, 22]])

In [6]:
second_row = array[1]

In [7]:
print(second_row)

[20 21 22 23 24]


Exercise 6: Reversing Elements

In [8]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
reversed_array = array[::-1]

In [10]:
print(reversed_array)

[9 8 7 6 5 4 3 2 1 0]


Exercise 7: Identity Matrix

In [11]:
identity_matrix = np.identity(4)

In [12]:
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Exercise 8: Simple Aggregate Functions

In [13]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
total = np.sum(arr)

In [15]:
average = np.mean(arr)

In [16]:
print("Sum:", total)
print("Average:", average)

Sum: 45
Average: 4.5


Exercise 9: Create Array and Change its Structure

In [17]:
import numpy as np

In [18]:
arr = np.arange(1, 21)

In [19]:
reshaped_arr = arr.reshape(4, 5)

In [20]:
print(reshaped_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Exercise 10: Conditional Selection of Values

In [21]:
import numpy as np

In [22]:
arr = np.arange(10)

In [23]:
odd_numbers = arr[arr % 2 == 1]

In [24]:
print(odd_numbers)

[1 3 5 7 9]
